blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name = 'home'),
    path('post/create/',views.CreateNewPostView.as_view(),name = 'create'),
    path('login/',views.LoginPage.as_view(), name = 'login'),
    path('logout/',views.LogoutPage.as_view(),name = 'logout'),
    path('post/<int:pk>/',views.PostDetailView,name= 'detail'),
    path('drafts/',views.DraftList.as_view(),name = 'drafts'),
    path('post/update/<int:pk>',views.PostUpdateView.as_view(),name = 'update'),
    path('post/delete/<int:pk>',views.PostDeleteView.as_view(),name = 'delete'),
    path('post/publish/<int:pk>',views.publish_post_view,name='publish'),
    path('about/',views.AuthorView.as_view(),name = 'about'),
    path('post/<int:pk>/comment/new',views.CreateCommentView,name = 'new_comment'),
    path('post/<int:pk>/comment/all',views.CommentListView,name = 'all_comments'),
    path('comment/<int:pk>/delete',views.CommentDeleteView.as_view(),name = 'delete_comment'),
    


]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    
]

blog/models.py
from datetime import time
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = RichTextField(null =True)
    preview_text = models.TextField(max_length=500)
    preview_image_url = models.URLField(blank=True,null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments',on_delete=models.CASCADE)
    author_name = models.CharField(max_length=200)
    comment_message = models.CharField(max_length=100)
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk': self.post.pk})

    def publish(self):
        self.created_date = timezone.now()
        self.save()

    def __str__(self):
        return self.comment_message

blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','author','text','preview_text','preview_image_url')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author_name', 'comment_message',)

blog/views.py
from django.views.generic.base import TemplateView
from . forms import CommentForm, PostForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from . models import Post,Comment
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


# Create your views here.

class LoginPage(LoginView):
    template_name = 'admin/login.html'

class LogoutPage(LoginRequiredMixin,LogoutView):
    template_name = 'admin/logout.html'


class CreateNewPostView(LoginRequiredMixin,CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    form_class = PostForm

    # def get_success_url(self):
    #     return reverse_lazy('blog:post_detail')
    # I have added get_absolute_url in Model . So this is not required anymore for redirect.

class PostListView(ListView):
    paginate_by = 3
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = False).order_by('published_date').reverse()


# class PostDetailView(DetailView):
#     template_name = 'blog/post_detail.html'
#     model = Post
#     context_object_name = 'post'

#     def get_queryset(self):
#         print(self.request)
#         post = get_object_or_404(Post,pk = self.kwargs['pk'])
#         # post.comments = post.comments.all().order_by('created_date').reverse()
#         return post;

# Class based view is not comfortable in this case

def PostDetailView(request,pk):
    post = get_object_or_404(Post,pk= pk)
    context = {}
    context['post'] = post
    context['top_comments'] = post.comments.all().order_by('created_date').reverse()[:5]
    return render(request,'blog/post_detail.html',context)



class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_edit.html'
    context_object_name = 'post'
    redirect_field_name = 'blog/post_detail.html'


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    template_name = 'blog/post_delete_confirm.html'
    success_url = reverse_lazy('blog:home')
    context_object_name = 'post'

@login_required
def publish_post_view(request,pk):
    post = get_object_or_404(Post,pk = pk)
    post.publish()
    return redirect('blog:home')

class DraftList(LoginRequiredMixin,ListView):
    paginate_by = 3
    model = Post
    template_name = 'blog/draft.html'
    context_object_name = 'posts'

    def get_queryset(self):
        posts = Post.objects.filter(published_date__isnull = True).order_by('created_date').reverse()
        return posts


class AuthorView(TemplateView):
    template_name = 'blog/author.html'


def CreateCommentView(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.publish()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})

def CommentListView(request,pk):
    post = get_object_or_404(Post,pk = pk)
    context = {}
    paginator = Paginator(post.comments.all().order_by('created_date').reverse(), 5) # Show 5 comments per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj
    return render(request,'blog/comment_list.html',context=context)

class CommentDeleteView(LoginRequiredMixin,DeleteView):
    model = Comment
    template_name = 'blog/comment_delete_confirm.html'
    context_object_name = 'comment'

    def get_success_url(self):
        return reverse_lazy('blog:detail',kwargs = {'pk': self.object.post.pk })

templates/base/base.html
<!DOCTYPE html>
{% load static %}

<html>
<title>My Blog</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sticky-footer/">

<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

<body class="w3-light-grey">

 <div class="wrapper">

<!-- Header -->
<header class="w3-container w3-dark-grey w3-center w3-padding-32"> 
  <h1><b>MY BLOG</b></h1>
  <h3>
  <p>Welcome to the blog of <span class="w3-tag">Bob</span></p>
  </h3>
  <h4>
		<a class="btn btn-primary" href="{% url 'blog:home' %}">Home</a>
		<a class="btn btn-primary" href="{% url 'blog:about' %}">About</a>

	
	{% if user.is_authenticated and user.is_superuser %}
		<a class="btn btn-primary" href="{% url 'blog:create' %}">Create Post</a>
		<a class="btn btn-primary" href="{% url 'blog:drafts' %}">Drafts</a>
		<a class="btn btn-primary" href="{% url 'admin:index' %}">Admin Site</a>
		<a class="btn btn-primary" href="{% url 'blog:logout' %}">Logout</a>
	{% else %}
	    <a class="btn btn-primary" href="{% url 'blog:login' %}">Admin Login</a>

	{% endif %}
  </h4>
</header>


	{% block base %}
	{% endblock %}


<div class="push"></div>
</div>


<!-- Footer -->
<footer class="footer w3-container w3-dark-grey w3-padding-32 w3-margin-top">
  <center>
  <h5>
  	<p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a> and <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a></p>
	<p> Made with &#10084;&#65039; by Debanjan Saha
  </center>
  </h5>
</footer>

</body>
</html>

templates/blog/author.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}


<!-- Grid -->
<div class="w3-row">

<!-- Introduction menu -->
<div class="w3-col l1"><p></p></div>
<div class="w3-col l4">
    <div class="w3-card w3-margin w3-margin-top">
     <img src="{% static '/images/myself.jpg' %}" style="width:100%;height:270px">
    </div>
</div>

<div class="w3-col l6">
  <!-- About Card -->
  <div class="w3-card w3-margin w3-margin-top">
    <div class="w3-container w3-white">
      <h4><b>About Me</b></h4>
      <p>
      Debanjan Saha
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.     
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
      </p></div>
  </div>

<div class="w3-col l1"><p></p></div>

  


 
  
<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>

{% endblock %}

templates/blog/comment_delete_confirm.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}

  <div class="container">
     <div class="jumbotron">
      <form action="" method="post">{% csrf_token %}
    
       <div class="alert alert-success" role="alert">
        Are you sure you want to delete?
        </div>
          <input class='btn btn-success' type="submit" value="Yes"/>
          <a href={% url 'blog:detail' comment.post.pk %} class='btn btn-danger'>No</a>

        </form>
    </div>

  </div>

{% endblock %}
       
     

templates/blog/comment_form.html
{% extends 'base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block base %}

  <div class="container">


    <center><h1>New Comment</h1></center>
    <form method="POST">
    {% csrf_token %}
    {{ form.media }}

    <div class="form-row">
        <div class="form-group col-md-12 mb-0">
            {{ form.author_name|as_crispy_field }}
        </div>
    </div>

   <div class="form-row">
        <div class="form-group col-md-12 mb-0">
            {{ form.comment_message|as_crispy_field }}
        </div>        
    </div>

    <div class="form-row">
        <div class="form-group col-md-4 mb-0"></div>

        <div class="form-group col-md-4 mb-0">
            <center>
            <button type="submit" class=" btn btn-success" >Post</button>
        </center>
        </div>  

        <div class="form-group col-md-4 mb-0"></div>

    </div>


     
    
    
</form>




  </div>

{% endblock %}

templates/blog/comment_list.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}


<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">


<!-- Grid -->
<div class="w3-row">


<!-- Introduction menu -->
<div class="w3-col l2"><p></p></div>

<div class="w3-col l8">
  
  <!-- Posts -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>All Comments</h4>
    </div>
    <ul class="w3-ul w3-hoverable w3-white">
    {% for comment in page_obj %}
        <li class="w3-padding-16">
        <span class="w3-medium"><b>Written by:</b> {{ comment.author_name }} on {{ comment.created_date }}</span><br>
        <span><b>Comment:</b> {{ comment.comment_message }}</span><br>
        {% if user.is_authenticated %}
        <span><b><a class=" btn btn-danger" href = "{% url 'blog:delete_comment' comment.pk %}">Delete Comment</a></b> </span>
        {% endif %}
      </li>
    {% endfor %}
    </ul>
  </div>
  <hr> 

   <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a class="btn btn-primary" href="?page=1">&laquo; First Page</a>
              <a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
         {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">Next Page</a>
            <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">Last Page &raquo;</a>
        {% endif %}
    </span>
    </center>
    </div>

<div class="w3-col l2"><p></p></div>

<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>


{% endblock %}

templates/blog/delete_confirm.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}

  <div class="container">
     <div class="jumbotron">
      <form action="" method="post">{% csrf_token %}
    
       <div class="alert alert-success" role="alert">
        Are you sure you want to delete?
        </div>
          <input class='btn btn-success' type="submit" value="Yes"/>
          <a href={% url 'blog:detail' custom_object.pk %} class='btn btn-danger'>No</a>

        </form>
    </div>

  </div>

{% endblock %}
       
     

templates/blog/draft.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}


<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">


<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l2 s12">
  <p></p>
</div>

<div class="w3-col l8 s12">
  
  	{% for post in posts %}

    
	  	<!-- Blog entry -->

  <div class="w3-card-4 w3-margin w3-white">
  <img src="{{ post.preview_image_url }}" style="width:100%;height:300px">
    <div class="w3-container">
      <h3><b>{{ post.title }}</b></h3>
      <h5>Published on <span class="w3-opacity">{{post.published_date}}</span></h5>
    </div>

    <div class="w3-container">
      <p>
	  	{{ post.preview_text }}
	  </p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p>
            <a class="btn btn-warning" href="{% url 'blog:detail' post.pk %}"><b>READ MORE »</b></a>
            <a class="btn btn-primary" href="{% url 'blog:publish' post.pk %}"><b>Publish</b></a>
          </p>

        </div>
        <div class="w3-col m4 w3-hide-small">
          <span class="w3-padding-large w3-right"><b>Comments</b> <span class="w3-badge">{{ post.comments.count }}</span></span>
        
        </div>
      </div>
    </div>
  </div>
  <hr>
	{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary" href="?page=1">&laquo; First Page</a>
            <a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">Next Page</a>
            <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">Last Page &raquo;</a>
        {% endif %}
    </span>
    </div>


<div class="w3-col l2 s12">
  <p></p>
</div>


  
<!-- END BLOG ENTRIES -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>


{% endblock %}

templates/blog/index.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}


<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">


<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l2 s12">
  <p></p>
</div>

<div class="w3-col l8 s12">
  
  	{% for post in posts %}

    
	  	<!-- Blog entry -->

  <div class="w3-card-4 w3-margin w3-white">
  <img src="{{ post.preview_image_url }}" style="width:100%;height:300px">
    <div class="w3-container">
      <h3><b>{{ post.title }}</b></h3>
      <h5>Published on <span class="w3-opacity">{{post.published_date}}</span></h5>
    </div>

    <div class="w3-container">
      <p>
	  	{{ post.preview_text }}
	  </p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p>
            <a class="btn btn-warning" href="{% url 'blog:detail' post.pk %}"><b>READ MORE »</b></a>
          </p>

        </div>
        <div class="w3-col m4 w3-hide-small">
          <span class="w3-padding-large w3-right"><b><a href = "{% url 'blog:all_comments' post.pk %}">Comments</a></b> <span class="w3-badge">{{ post.comments.count }}</span></span>
        
        </div>
      </div>
    </div>
  </div>
  <hr>
	{% endfor %}

  
  <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a class="btn btn-primary" href="?page=1">&laquo; First Page</a>
              <a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
         {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">Next Page</a>
            <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">Last Page &raquo;</a>
        {% endif %}
    </span>
    </center>
    </div>

<div class="w3-col l2 s12">
  <p></p>
</div>


<!-- END BLOG ENTRIES -->
</div>


<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>


{% endblock %}


templates/blog/post_delete_confirm.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}

  <div class="container">
     <div class="jumbotron">
      <form action="" method="post">{% csrf_token %}
    
       <div class="alert alert-success" role="alert">
        Are you sure you want to delete?
        </div>
          <input class='btn btn-success' type="submit" value="Yes"/>
          <a href={% url 'blog:detail' post.pk %} class='btn btn-danger'>No</a>

        </form>
    </div>

  </div>

{% endblock %}
       
     

templates/blog/post_detail.html
{% extends 'base/base.html' %}

{% load static %}

{% block base %}

<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l8 s12">
 

 	<!-- Blog entry -->

  <div class="w3-card-4 w3-margin w3-white">
  <img src="{{ post.preview_image_url }}" style="width:100%;height:300px" alt="Error! Cant Load Image">
    <div class="w3-container">
      <h3><b>{{ post.title }}</b></h3>
    </div>

    <div class="w3-container">
      <p>
	  	{{ post.text|safe }}
	  </p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p>
          {% if user.is_authenticated %}
            <a class="btn btn-success" href="{% url 'blog:update' post.pk %}"><b>Edit</b></a>
            <a class="btn btn-danger" href="{% url 'blog:delete' post.pk %}"><b>Delete</b></a>
          {% endif %}  
          
          {% if post.published_date is None %}
            <a class="btn btn-warning" href="{% url 'blog:publish' post.pk %}"><b>Publish</b></a>
          {% endif %} 
          
          {% if post.published_date is not None %}
            <a class="btn btn-primary" href="{% url 'blog:new_comment' post.pk %}"><b>Comment</b></a>
          {% endif %} 

          </p>
        </div>
        <div class="w3-col m4 w3-hide-small">
          <a href="{% url 'blog:all_comments' post.pk %}"><span class="w3-padding-large w3-right"><b>All Comments</b> <span class="w3-badge">{{ post.comments.count }}</span></span></a>
        </div>
      </div>
    </div>
  </div>
  <hr>
<!-- END BLOG ENTRIES -->
</div>

<!-- Introduction menu -->
<div class="w3-col l4">
  
  <!-- Posts -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Last 5 comments</h4>
    </div>
    <ul class="w3-ul w3-hoverable w3-white">
    <h5>
    {% for comment in top_comments %}
        <li class="w3-padding-16">
        <span class="w3-large"><b>Written by:</b> {{ comment.author_name }}</span><br>
        <span><b>Comment:</b> {{ comment.comment_message }}</span>
      </li>
    {% endfor %}
    </h5>
    </ul>
  </div>
  <hr> 

<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>



{% endblock %}

templates/blog/post_edit.html
{% extends 'base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block base %}

  <div class="container">


    <center><h1>Edit Post</h1></center>
    <form method="POST">
    {% csrf_token %}
    {{ form.media }}

    <div class="form-row">
        <div class="form-group col-md-8 mb-0">
            {{ form.title|as_crispy_field }}
        </div>
        
        <div class="form-group col-md-4 mb-0">
            {{ form.author|as_crispy_field }}
        </div>
    </div>
    
    <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                {{ form.preview_image_url|as_crispy_field }}
            </div>
            

    </div>

   <div class="form-row">
        <div class="form-group col-md-10 mb-0">
            {{ form.text|as_crispy_field }}
        </div>

         <div class="form-group col-md-2 mb-0">
            {{ form.preview_text|as_crispy_field }}
            
            <center>
               <p><button type="submit" class=" btn btn-success" >Save</button></p>
               <p><button href={% url 'blog:detail' post.pk %} class=" btn btn-danger" >Cancel</button></p>
            </center>
        </div>
    </div>
    
    </form>




  </div>

{% endblock %}

templates/blog/post_form.html
{% extends 'base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block base %}

  <div class="container">


    <center><h1>New Post</h1></center>
    <form method="POST">
    {% csrf_token %}
    {{ form.media }}

    <div class="form-row">
        <div class="form-group col-md-8 mb-0">
            {{ form.title|as_crispy_field }}
        </div>
        
        <div class="form-group col-md-4 mb-0">
            {{ form.author|as_crispy_field }}
        </div>
    </div>
    
    <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                {{ form.preview_image_url|as_crispy_field }}
            </div>
            

    </div>

   <div class="form-row">
        <div class="form-group col-md-10 mb-0">
            {{ form.text|as_crispy_field }}
        </div>

         <div class="form-group col-md-2 mb-0">
            {{ form.preview_text|as_crispy_field }}
            
            <center>
               <button type="submit" class=" btn btn-success" >Post</button>
            </center>
        </div>
    </div>
    
    </form>




  </div>

{% endblock %}